### ISSUE TITLE
Potion stacks break Industial Foregoing's potion brewer

### ISSUE THREAD

**Issue by VizuaaLOG** [FTBTeam/FTB-Revelation-2#125]
* **Modpack Version**: 2.5.0

* **Issue**: Unsure of what mod is causing potions to stack but it's preventing the potion brewer from working. There is an open issue for it but in the meantime what mod adds the ability to stack potions? Wondering if this is something I can disable.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**:  Industrial Foregoing [Open issue](https://github.com/Buuz135/Industrial-Foregoing/issues/427)

**Edit** A temporary fix is to disable potion stacking from within Quark. Under the stackable_items config option change Potions to 1.

**Comment by Nividica** [comment]
Just want to note that the issue also affects the regular brewing stand as reported here:
https://github.com/Vazkii/Quark/issues/1024

And that Vazkii has since removed the option in the sourcecode:
https://github.com/Vazkii/Quark/commit/607a31025cebef22be01f6bb5eeec965285f48c7

For anyone else who finds themselves here, if editing the config is a pain you can also run the following command then restart:
`/quarkconfig tweaks "stackable items" "I:Potions" 1 save`

**Comment by tfox83** [comment]
fixed in 2.7.0
