### ISSUE TITLE
Players cannot join server

### ISSUE THREAD

**Issue by AlwaysSil3nt** [FTBTeam/FTB-Revelation-2#151]
* **Modpack Version**: 2.6.0 

* **Issue**: I, as host, can join the server, but other players join, cannot load in correctly, and get disconnected within seconds

* **Link to Log or Crash File Paste**: https://pastebin.com/Ld9fdf4C

* **Is it Repeatable?**: This happens everytime I launch the server, no matter what.

I have tried every single fix I can think of and have done literal hours of research to find a fix for this, but to no avail. Thanks in advance!

**Comment by rune-san** [comment]
This usually isn't a mod bug, but rather instances where servers either don't have enough resources, or the connection to the server, or from the client is too slow, dropping packets, etc. I'd check and verify that it genuinely is multiple other players in multiple other geographic locations that can't connect. If they can't, your server may be struggling to log them in within the 30 second timeout, or you may have connection quality issues that prevents this.

If it's only one user, or a minority, it's usually because the clients don't have enough resources, or again, they have a poor connection to your server.

As a bandaid, installing the RandomPatches mod can provide a way to override the 30 second timeout and allow users with slower systems to connect (or slower servers to process the login), but it won't address the quality of life issues from poor connections and inadequate resources.
