### ISSUE TITLE
Clean Server not starting with latest version

### ISSUE THREAD

**Issue by PhilippCl** [FTBTeam/FTB-Revelation-2#174]
* **Modpack Version**: 2.7.0 with FORGE 14.23.5.2796 (latest)

* **Issue**: The Server is crashing while initial Loading

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/91a055e4

* **Is it Repeatable?**: Yes, just try to setup a server on the latest version

* **Mod/s Affected**: LetsEncryptCraft

* **Known Fix**: -

**Comment by rune-san** [comment]
Thing that sticks out right away is you don't have nearly enough RAM assigned:
`JVM Flags: 7 total; -Xmx2048M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=5 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10`

Change it to 3GB (-Xmx3G or -Xmx3072M) minimum. I'd recommend 4G if you have it. But 2G is not enough.

**Comment by PhilippCl** [comment]
Yeah, I forgot to change that as I first encountered this error while updating my normal Server and then created a new one to see if the error still shows up.

I changed it to assign 6GB of RAM but sadly that did not change anything.
Basically the crash report is the same except this line(Because of the RAM change):

```
JVM Flags: 7 total; -Xmx6144M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=5 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
```

**Comment by rune-san** [comment]
Is this repeatable on this system, or thus far is this the only instance that's been attempted on this system? I haven't deployed 2.7 yet, so I decided to spin up a default world on one of my spare VMs and it kicked right up after about 5 minutes. So it would seem that the issue would be with the deployment itself (perhaps something in Lets Encrypt is now stuck in the process after the first 2G run), or there's something corrupted in general in the deployment.

If you try a fresh install on that same system using at least 3G of RAM, does the same issue occur? What does it's pastebin look like?

**Comment by PhilippCl** [comment]
I just completely wiped the installation and downloaded everything again also I changed the assigned ram amount before the first start. Still no change. I'd like to point out that the old Version 2.6.0 runs fine on the System.

https://paste.feed-the-beast.com/view/46daa54f

**Comment by rune-san** [comment]
Alright, looking at the core of the Exception getting thrown:

`java.lang.NumberFormatException: For input string: "03-Ubuntu"`

Is that your hostname? My server naming if formatted also with letters, numbers, and hyphens, so I don't know why mine would work, and yours would not. Unless that input string is for something else?

**Comment by rune-san** [comment]
Actually, I'm being silly. I see now that "03-Ubuntu" is the tail end of your java version.

`Java Version: 1.8.0_03-Ubuntu, Oracle Corporation`

letsencryptcraft is trying to parse your Java version, and failing because it contains that incorrect build information. You're hitting at least a variant of this Ubuntu bug:

[https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1550244](url)

Is there an update for your java install? What happens if you run something like

`sudo apt-get install default-jre`

Does it offer a new JRE?

**Comment by PhilippCl** [comment]
Atm I can't try that because more Services on that System rely on Java. The installed Version is:
```
OpenJDK Runtime Environment (build 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03)
OpenJDK 64-Bit Server VM (build 25.03-b03, mixed mode)
```

The older Version 2.6.0 runs smoothly and I had to use this Java Version for that. So maybe some Bug with the Java/System/FTB Version which are incompatible cause of a parsing error in letsencryptcraft ?

I found a similar issue on the letsencryptcraft git repository: [LetsEncryptCraft Issue 1](https://github.com/Cloudhunter/LetsEncryptCraft/issues/1). This seems to be the Problem I got myself.

**Comment by rune-san** [comment]
I do not believe that the OpenJDK Runtime Environment is the version getting parsed. It's the OpenJDK Version. For instance, using the default Debian package, this is the current version it would display:

```
java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

The Java versioning should not have any of that "extra" stuff passed through it. It seems some packages in Ubuntu in your case at least used to do it, and it sounds like RHEL has that, even though at least on the RHEL 8 Beta versions, if you install Java, it is *not* doing that:

```
java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
This look like the author of letsencryptcraft didn't know that some releases of Oracle Java and OpenJDK are not writing their versioning in "standard" methods. Still, installing the standard OpenJDK would likely resolve this issue.

The reason you're getting this now and not before is because LetsEncryptCraft was not added to FTB Revelation 2 until 2.7. None of its mods are doing checks that integer parse for versions (and indeed, I don't think the most mods check or care, and the ones that do, are only looking for major families, like Java 8 vs. Java 7).

**Comment by PhilippCl** [comment]
Sorry, for the "closed" and "reopened" above. Accidentally clicked the wrong button ;)
----
I installed a version without that string ('03-Ubuntu') in the Version Number and as expected: it worked.

But the issue with LetsEncryptCraft is still there and from my Point of View it looks like it is not maintained currently. Maybe FTB Revelations or Forge should not use it ? I don't now rly.

I will update the Issue Title to better reflect the error and then I will close this issue. It is not 100% Revelations related and definitely a LetsEncryptCraft issue. I still think this error should have popped up while Beta Testing the new release with different Java Version from different repository and so on.

Thanks @rune-san for your help! 👍
