### ISSUE TITLE
jei error

### ISSUE THREAD

**Issue by shadowbf** [FTBTeam/FTB-Revelation-2#179]
* **Modpack Version**: 2.7.0
* **Issue**: tried loading mod from the curse app got this error.

* **Link to Log or Crash File Paste**: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

https://pastebin.com/55ZmkazU

* **Is it Repeatable?**: happens everytime
* **Mod/s Affected**: jei

**Comment by BubbaDough** [comment]
I've had the same issue installing via the Twitch Launcher, it consistently crashes when registering plugins for Ender IO's Dark Steel Upgrades, but reads as a crash caused by JEI.  Checking the crash log, I see "Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded", followed by 32 lines listing where that problem occurred. (similar to the log in the original post) 
This also occurs for me every time, no matter how much I reboot, reinstall, or repair the installation.  Other modpacks install and load just fine.

**Comment by Maxus1998** [comment]
Log says:
-- System Details --
Details:
    Minecraft Version: 1.12.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 983529240 bytes (937 MB) / 2863661056 bytes (2731 MB) up to 2863661056 bytes (2731 MB)

Try assigning more ram in the twitch launcher or the minecraft launcher profile (profile resets evrey time twitch launches minecraft so I would recommend changeing it in the twitch launcher)

**Comment by tomtenberge** [comment]
as soon as you see "Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded", you know you ran out of memory, and need to allocate more.

i see that a lot with modpacks, that they use the "use system default" for the amount of memory, instead of stating a minimal amount.
