### ISSUE TITLE
2.7.0 minecraft not starting - LetsEncryptCraft Parsing error

### ISSUE THREAD

**Issue by Adrian-Turjak** [FTBTeam/FTB-Revelation-2#182]
Modpack Version: 2.7.0 with FORGE 14.23.5.2796 (latest)

Issue: Certain linux distributions or certain versions of the OpenJDK have slightly different version formats and the way LetsEncryptCraft was parsing that breaks either the server or client.

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/91a055e4

Is it Repeatable?: Yes, on a Linux OS with the different version format.

Mod/s Affected: LetsEncryptCraft

Known Fix: Upgrade the mod version of LetsEncryptCraft, as the newer version uses regex to now correctly parse the most common variant of the version format.

**Comment by Adrian-Turjak** [comment]
Creating a new issue since the person who posted the last one closed it before it was actually fixed (see #174 )

Relates to:
https://github.com/Cloudhunter/LetsEncryptCraft/issues/1

Which has now been fixed.

**Comment by rune-san** [comment]
As discussed in the previous Bug you mentioned, the modpack is absolutely not broken in Linux. The only place it is broken on Linux is on Linux distros that break userspace by altering the java version with anything other than the Major/Minor version. Unfortunately it appears that Solus is one of the offenders, appending "-solus" to the Java version. While this is better than others (like the 03-Ubuntu bug), it is still unnecessary and creates issues like this. Major/Minor version checking is important, and by breaking that, the distros leave no meaningful way to decrypt that information, especially because when they break it, they all arbitrarily break it in a different fashion.

For instance with Solus, if instead of using the Package Repository's Java, you use Oracle's Java as mentioned on their [Help Center Article](https://getsol.us//articles/software/java/en/), the java version shows 1.8.0_202, exactly as it should. It would parse with cloudhunter's original code correctly, just as it currently does with current versions of Ubuntu, Debian, RedHat, CentOS, and Fedora.

Cloudhunter's fix gets around the issue by essentially saying "I can't figure out what the Java version is, so I'm just going to hope you're running at leave minor version 110 and run anyways". Considering that Minecraft packages Minor version 74 by default, I'm concerned that he may be opening himself up to getting a different set of bugs, because a combination of appended broken Java versions will end up having him run his code against versions of Java that aren't able to run.

The "proper" fix for this issue is dealing with it just like Ubuntu did, and filing a bug report with Solus asking them to remove the appending information from the Java version so that userspace isn't broken like it is currently in that distro.

**Comment by Adrian-Turjak** [comment]
@rune-san 
Problem is that Solus clearly isn't the only place being hit by this. The original bug report on LetsEncryptCraft is from a RedHat user: `191-1-redhat`, and clearly someone using Ubuntu was hit by this recently. It isn't broken for all Linux distros, but on enough of them that this is a problem.

I fully intend to file a bug report with Solus, but the fix in LetsEncryptCraft is still needed as an interim until enough people bug all the various distros that are affected. Sadly that will take longer than just fixing the parsing.

As for the fix he did do, it's actually perfectly sufficient and actually works for me on Solus. I've tested it with version 2.7.0 of the modpack, just by replacing the mod version of LetsEncryptCraft. His regex is correctly handling the case and finding the versions, and not defaulting to assuming 110 as you seem to think would happen. It also works when the version doesn't have anything appended to it. It would only break in a situation when a linux distro did something more than append to the version.

Here you can play with the regex: https://regexr.com/475e6

His regex correctly splits the major/minor version groups and ignores anything appended to it that isn't a number. Major/minor version checking is only broken if you don't use regex to parse for what you need.

The fix is just update LetsEncryptCraft in the FTB modpacks that use it, pure and simple.

**Comment by Adrian-Turjak** [comment]
As someone working in the linux space... sadly fragmentation, and assuming fragmentation are the defaults. That's why I do everything in containers these days (including running my minecraft servers!). I only hit this issue with the client because I run Solus as my main linux OS.

But I'm curious, why are you saying `03-Ubuntu` wouldn't work? The new code would treat that as `3` and then apply the certs. Are you saying that `3` isn't the correct minor version in that case?

At any rate, I'll edit the bug report to be more specific that it is only affecting some Linux distros, but that we should up update the mod anyway.

And yeah, I checked various distro's too, all the major ones I know people around me use in their latest version looked clean.

**Comment by M0rtale** [comment]
> sudo apt-get uninstall openJDK
> sudo apt-get install openjdk-8-jdk
> sudo apt-get install openjdk-8-jre-headless

This should fix.

**Comment by Adrian-Turjak** [comment]
@M0rtale 
That solved it for the original bug poster, but not for me as I'm not on Ubuntu. :P 

As rune-san already mentioned, I'd have to follow:
https://getsol.us//articles/software/java/en/

Which i'd prefer not to as then I manually have to keep java updated.

Just manually replacing the version of LetsEncryptCraft with the newest version also works and breaks nothing else in the modpack.
