### ISSUE TITLE
CRASH / Freeze at launch ( black screen / white mojang screen )

### ISSUE THREAD

**Issue by Rokxtard** [FTBTeam/FTB-Revelation-2#203]
* **Modpack Version**: forge-14.23.5.2796 FTB Revelation version 2.7.0

* **Issue**: game freeze at launch, at black screen or just after, the white screen with "mojang"

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/c418afeb 

* **Is it Repeatable?**: yes, each time i want to launch the game

Hi,
updated my java, PC rebooted, tried allocate more GB to Minecraft.... nothing worked,
so im here.

I did some research, nothing helped.

If you can see the problem, could be great.

All suggestions welcome.

Thanks in advance.

**Comment by goodoluncleBelhem** [comment]
I've had the same problem, been working on it for 4 hours now. Nothings working yet

**Comment by N3xed** [comment]
The log says java didn't have enough memory. In the modpack page it says that you have

**Comment by N3xed** [comment]
The log says minecraft crashed because of too little memory. On the modpack [page](https://www.curseforge.com/minecraft/modpacks/ftb-revelation) it says that 
a minimum 4GB of memory is recommended.
So you either have to allocate 4+GB of RAM to minecraft, or if you don't have enough memory in your system, get some more.

You can allocate memory to minecraft in the Twitch Launcher. Go to `Settings`, `Minecraft`. In `Java Settings` at the bottom, you can increase the allocated memory.
