### ISSUE TITLE
EnderIO Redstone Conduits Input/Output is inverted

### ISSUE THREAD

**Issue by Theagle43** [FTBTeam/FTB-Revelation-2#217]
* **Modpack Version**: 2.7.0
* **Issue**: EnderIO Redstone Conduits have their Inputs and Outputs inverted. For example, if I have a conduit set to "Input" on Blue, a blue arrow pointing *out* will appear on the conduit. Conduit also behaves as if "Output" was set to blue, so this is not just a graphical bug.

![2019-04-23_19 26 53](https://user-images.githubusercontent.com/8277367/56629407-192f2a80-6602-11e9-9ca3-d733de984324.png)
![2019-04-23_19 58 41](https://user-images.githubusercontent.com/8277367/56629455-3e239d80-6602-11e9-938f-bd9088e5d76b.png)

* **Link to Log or Crash File Paste**: No crash!

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: EnderIO

* **Known Fix**: None

**Comment by KaizenNeko** [comment]
If I recall correctly, this behavior is correct. Input is not the redstone signal going in to a machine, it's the signal into the conduit. Output is the signal outputted to the machine.  Basically a lever would be the input and a RFTools Builder (as an example because I can't make out what the block is in your screen shot is) is the output.

Basically think of redstone conduit as repeater.
