### ISSUE TITLE
Game crashes while compiling modpack

### ISSUE THREAD

**Issue by EvilGnomeSausage** [FTBTeam/FTB-Revelation-2#231]
* **Modpack Version**: <3.0.1>

* **Issue**: <Game crashes upon initialization of the modpack at first launch, won't complete>
 
* **Link to Log or Crash File Paste**: <The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei) https://paste.feed-the-beast.com/view/0f59ab4c>

* **Is it Repeatable?**: <!Every time>

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by rune-san** [comment]
We see this sort of error get posted quite a bit, but it's readily fixed as long as you have enough system resources available. The error log shows the problem:

**Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded**
Error showing your Java Machine ran out of RAM trying to load.

`Details:
        Minecraft Version: 1.12.2
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_51, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 618983136 bytes (590 MB) / 2863661056 bytes (2731 MB) up to 2863661056 bytes (2731 MB)
        JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m`

The things I see are **-Xmx3072m** and **1.8.0_51**

You have your Java VM set for 3GB of RAM. And on the front page for FTB Revelation:

* A minimum of 4 GB of RAM is recommended for clients as well as servers for best performance

* Latest version of JAVA 8 is recommended 
* JAVA 9 is NOT supported

Increase your Memory allocation for your Minecraft instance to at least 4GB and retest. :) While you're at it, I'd also make sure you have the latest version of Java installed from www.java.com. The version you have currently is very old.

Let us know how it goes once you retest with the minimum recommended Allocated Memory set. :)
