### ISSUE TITLE
Crash due to server tick loop upon loading world

### ISSUE THREAD

**Issue by TragicRegent** [FTBTeam/FTB-Revelation-2#235]
* **Modpack Version**: 3.0.1

* **Issue**: Created a world. Played it for a day or so. Go to load it. It loads for a while. Flashes back to main menu then game crash. "It looks like you are using an unsupported modified version of the game." "The game crashed whilst exception in server tick loop." I make a new world. A day later it happens again.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/90ed0f20

* **Is it Repeatable?**: Yes. Every time I try to load a world.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Moondarker** [comment]
Can you upload the affected world somewhere?

**Comment by TragicRegent** [comment]
Sure. Here's the second one.

[New World.zip](https://github.com/FTBTeam/FTB-Revelation-2/files/3219407/New.World.zip)

**Comment by Moondarker** [comment]
Well, it's really weird. Could you try to replace this file and see if crash occurs?
[New World - tbr.zip](https://github.com/FTBTeam/FTB-Revelation-2/files/3220951/New.World.-.tbr.zip)

**Comment by TragicRegent** [comment]
That seems to have fixed it. Thanks!

**Comment by Moondarker** [comment]
We fixed the effect, but haven't find the cause yet, I suggest to leave this issue open until authors do smth about it :)
I'm just a stranger who's trying to help out a bit

**Comment by rune-san** [comment]
This is related to a bug that's existed for some time under MineTogether. According to the issue it's been fixed in dev, but there hasn't been a a full release since last August. According to that issue, if you don't use MineTogether, then simply deleting the MineTogether config file out of the configs folder should get your server running again. CreeperHost/CreeperHostGui#61
