### ISSUE TITLE
Failing to load after update

### ISSUE THREAD

**Issue by Mesqi** [FTBTeam/FTB-Revelation-2#236]
Version: Ftb Revelation 3.0.1

Issue: After the update 5 days ago whenever I try to load my save this appears: https://gyazo.com/60567ec4f8d2be4bde3a61e366a2c949

Also, there's no crash log because this isn't a crash, but is it normal for that many entries to be missing after a small update?

**Comment by rune-san** [comment]
What did you update from? It states on the 3.0 Release Page that a world reset would be required to move to 3.x.x: https://www.feed-the-beast.com/projects/ftb-revelation/files/2711066
"*World Resets Required to update to 3.X.X"

I ask this because your screenshot specifically calls out objects from the Traverse and Roots 2 mods, two mods that were removed in the migration to 3.0 and would not have been in your Save if you were using a 3.x or newer world.

It appears that you are using a World Save from 2.X.X, in which case you won't be able to use this world in 3.X.X.

**Comment by Mesqi** [comment]
ohhhh I see, I missed that line, thank you man, gonna downgrade do 2.7 then.
