### ISSUE TITLE
The game crashed whilst exception in server tick loop

### ISSUE THREAD

**Issue by EvilGnomeSausage** [FTBTeam/FTB-Revelation-2#247]
* **Modpack Version**: 3.0.1

* **Issue**:  Been playing on the same world for a 1-2 weeks now, and I went to launch the world I've been playing on and now it crashes. Nothing's changed that I'm aware of. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/dce11948

The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineTogetherServer (minetogetherserver)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by Moondarker** [comment]
Take a look at #235, but don't close this one

**Comment by EvilGnomeSausage** [comment]
Does that mean I should comment over there? All I see at first glance is someone getting their world fixed manually.

**Comment by rune-san** [comment]
This is related to a bug that's existed for some time under MineTogether. According to the issue it's been fixed in dev, but there hasn't been a a full release since last August. According to that issue, if you don't use MineTogether, then simply deleting the MineTogether config file out of the configs folder should get your server running again. CreeperHost/CreeperHostGui#61

**Comment by EvilGnomeSausage** [comment]
Awesome! Has anyone figure out why it happens out of the blue? If I delete the config file, will it come back at some point? 

Edit: Also, will it be easy enough to get MineTogether back in if it's fixed later? I've never used it so I don't think I'll miss it but it's nice knowing I can get it back if I want to.

Edit 2: Figured it'd be wise to let you know that deleting the config doesn't seem to help me at all. Still complains about an exception with minetogetherserver.
