### ISSUE TITLE
ftb continuum project page link here

### ISSUE THREAD

**Issue by hinchy34** [FTBTeam/FTB-Revelation-2#256]
The issues link on ftb contiuum links here, to revelation 2. https://www.feed-the-beast.com/projects/ftb-continuum

**Comment by CitiesXL2815** [comment]
this issue is nothing to do with FTB Revelation Issue Tracker take it to FTB Continuum Issue Tracker

**Comment by hinchy34** [comment]
I did, but it seems they abandoned that 
failed abortion of a pack. Both packs are authored by FTB.

**Comment by CitiesXL2815** [comment]
yea they where signed to different pack issues you must think that continuum has it own issue tracker they will not listen to another pack like continuum that's not related to revelation that's why FTB open different issue tracker so people send right tracker to the issues in the packs if people don't mark the right pack then the dev's will think not enough info and close the issue if not relate to revelation they close it as well
