### ISSUE TITLE
Super Easy Crafting Table Item Duplication

### ISSUE THREAD

**Issue by drd-dev** [FTBTeam/FTB-Revelation-2#262]
* **Modpack Version**: 3.0.1
* **Issue**: If the player shift clicks a crafted item in a crafting table with a full inventory, they then can normal left click an infinite amount of times to duplicate the crafted item. as long as there isn't a place in their inventory for the item to go. [Video](https://www.youtube.com/watch?v=GW69RQN1tm4&feature=youtu.be)
* **Is it Repeatable?**: Yes
* **Mod/s Affected**: All?

**Comment by chaz9124** [comment]
I havent been able to replicate this, using must updated version of FTB Revelation

**Comment by Frolist** [comment]
i can confirm this i tried it too and it work

**Comment by DoragonKeiyou** [comment]
For Server Owners, this dupe bug was reported and fixed with a newer version of FastWorkbench.  Your options are to update that mod specifically, or if you run a server with the modpack containing the bugged version itself, change a line in the config for fastbench.cfg, line 8 to "false" instead of "true".

I would also suggest Revelations to update to 3.0.2 with this FastWorkbench updated due to it being a game breaking duplication glitch.

**Comment by tfox83** [comment]
Fixed in 3.1.0
