### ISSUE TITLE
SERVER CRASHED

### ISSUE THREAD

**Issue by Mooreaoth** [FTBTeam/FTB-Revelation-2#270]
FTBRevelation-3.0.1-1.12.2
[crash-2019-07-03_09.41.37-server.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/3360628/crash-2019-07-03_09.41.37-server.txt)
server not open

**Comment by rune-san** [comment]
Mooreath, please do not open duplicate issues. This is a copy of issue #269 including the fact that you did not fill out the issue template.

The Crash Report is the same, and the issue is the same. You are not assigning enough Memory to your Minecraft Server. This GitHub is for issues related to the game that may require pack fixes. If you're having issues figuring out how to configure your Minecraft Server, this is best suited for the community forums than here.

You can configure your server parameters from the settings file in folder where your Server is installed.

**Comment by Mooreaoth** [comment]
[crash-2019-07-14_19.07.35-server.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/3390197/crash-2019-07-14_19.07.35-server.txt)
olmadı verdiğim halde olmadı ?
