### ISSUE TITLE
Server not launching

### ISSUE THREAD

**Issue by Syntex70** [FTBTeam/FTB-Revelation-2#279]
* **Modpack Version**: <3.0.1 or 3.1.0>

* **Issue**: When i start a server through the forge universal.jar the server kind of loops on preinitialization.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/0306f743

* **Is it Repeatable?**: yes

* **Known Fix**: before it started after about 5-10 loops but now it completly dosen't work.

**Comment by tril0byte** [comment]
can't tell if this is actually looping or the normal startup - do you have a certain line that you know repeats so that we can search for it in the output?

Check that you assigned at least 4GB, but I recommend more, for MAX_RAM (in settings.bat or settings.sh) and wait at least 10 minutes - it takes a long time to start up.

**Comment by Syntex70** [comment]
"/game/bin/./mods for mods" appears about 2-3 times at the start. Plus i dont think it should be launching this long, when i launch the server on my pc through the "ServerStart.bat" file it launches in about 2 minutes. The server hosting im running it on gives a message that the server is not properly configured. Btw the server has 8 gb of ram assigned.

**Comment by rune-san** [comment]
What do you mean that you're launching the server through "forge universal.jar"? The Server is meant to be launched via the ServerStart.xx (Windows or Linux) script, which you note doing in your latest post on your PC. The JAR file is not set up to be directly launched. If the intention is to skip launching those, you're going to have to verify that you're at least emulating their functionality.

"$JAVACMD" -server -Xmx${MAX_RAM} ${JAVA_PARAMETERS} -jar ${FORGEJAR} nogui

The exported functions in the above command are referenced in either the settings-local.sh file (if you created and configured a specific settings file) or settings.sh if you did not. So if you're doing the above, what is the entire command you're using to launch the server?

**Comment by Syntex70** [comment]
Ok can you explain how can i get around using the "ServerStart.bat" and just use the forge jar instead?

**Comment by rune-san** [comment]
That process is going to change for every new release of FTB Revelation, and this GitHub is for dealing with issues pertaining to the pack itself, vs. a general support section for running servers in unsupported manners. If you're looking for a straightforward way of running FTB Revelation on a hosted provider without using the supported scripts, then I'd suggest an alternative hosting provider like Creeperhost that directly supports FTB Revelation. Otherwise, you're expected to use the ServerStart.sh (on Linux) script to start the server.

Some of the process to get around it is mentioned in my above post. Ultimately, "ServerStart.sh" calls this command (it also runs other checks, but if you're just looking for the command it runs to start the server, it's below:

"$JAVACMD" -server -Xmx${MAX_RAM} ${JAVA_PARAMETERS} -jar ${FORGEJAR} nogui

The portions above that must be filled in are the exported variables from your settings.sh file. As of 3.1, that's these:

export JAVACMD="java"
export MAX_RAM="2048M"
export JAVA_PARAMETERS="-XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=5 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10"
export FORGEJAR="FTBserver-1.12.2-14.23.5.2836-universal.jar"

Note that the above is free to change during any version change, and you'll have to adjust by checking the settings.sh file and adjusting your command. You'll also note that the MAX_RAM variable is by default incorrect. You'll want 4-6GB of RAM assigned to your instance vs. 2.

You'll match up and substitute (without quotes) for every variable to create your start command that you can then use on your server host.

This all of course depends on if your Server Hoster allows you to pass a full launch command like I referenced in my previous post. If all they want you to do is select a file, then chances are that the method you want to use is not going to work with FTB Revelation.

You can try to give the above a go and see if that allows your server to launch on your Hoster. That stated, the only option that's truly supported for issues arising during use is the ServerStart script.
