### ISSUE TITLE
Railcraft Metal Ingot/Block Integration Issues

### ISSUE THREAD

**Issue by dragonkid828** [FTBTeam/FTB-Revelation-2#286]
* **Modpack Version**: 3.0.1

* **Issue**: The intended variant of ingots/blocks is supposed to be Thermal Foundation, however crafting any metal block contained within Railcraft ends up with a Thermal Foundation block turning into Railcraft ingots. Some ingots also end up being crafted into Railcraft blocks when condensing.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yes. Take any (Thermal Foundation) block of a metal that is used in Railcraft (copper, tin, etc), put it in the crafting table, and the Railcraft ingot recipe takes precedence, however, in the other methods I've tested in creating them (casting from TiC Smeltery (block and ingot) and smelting dust in EnderIO alloy furnace) you get the Thermal Foundation variant.

* **Mod/s Affected**: Railcraft/Thermal Foundation

* **Known Fix**: Adding code to the unification scripts to remove the Railcraft block/ingot recipes should fix. I'm assuming just removing the recipes for the Railcraft ingots and blocks would do the trick and will attempt in the evening tomorrow and post the lines of code in an edit if they work. 

(Unrelated: another recipe that seemed to have squeaked through is the Buildcraft wood gear, which seems to overtake the Thermal Foundation one.)

**Comment by rune-san** [comment]
The Railcraft/Thermal Foundation issue was noted in #226 and should be fixed in 3.1.0.

https://www.feed-the-beast.com/projects/ftb-revelation/files/2746960

Changes:
**-Fixed Railcraft metal unfication**
-Fixed Yellorite/Uraninum ore gen levels
-Unhid genetic templates from JEI
-Added zinc to OreGen to make RC more early game
-Fixed CC modem recipe
-Fixed End Star recipe
