### ISSUE TITLE
Launches with no mods

### ISSUE THREAD

**Issue by anevilsomebody** [FTBTeam/FTB-Revelation-2#293]
Version 1.0

I've tried launching this modpack from Technic Launcher, and then I get into the world, and it's vanilla. No difference to the creative inventory, the worldgen, no JEI, not even the mods button on the title screen. It's all just vanilla. No crashes or anything.

https://paste.feed-the-beast.com/view/4b043a0c

I tried 3 or 4 times with the same result, so it is repeatable. I tried uninstalling and reinstalling to no avail. If you know of a fix, please let me know.

**Comment by CitiesXL2815** [comment]
for one version your using is false 3.1.0 is exact version in twitch launcher and idk if FTB supports integration with technic launcher anymore so use multimc or twitch to download the pack there

**Comment by MonfGeiger** [comment]
I recommend you use MultiMC than the twitch launcher; frankly, I think the twitch launcher is a bit too Process/CPU hogging when it runs, least in my opinion

MultiMC has less of an impact on your computer resource wise, you can point to any version of java you got installed/downloaded (depending if you got the portable version of java rather than the install.exe version), set java args with a cleaner interface, choose which mods you want disabled or enabled, add some mods to said modpack, the works. Frankly, I think MultiMC is easier to figure out and use than the twitch launcher
