### ISSUE TITLE
Forestry Thermionic Fabricator not accepting Wax Casts

### ISSUE THREAD

**Issue by afroJezuz** [FTBTeam/FTB-Revelation-2#308]
Client: 1.12.2 Beta: 3.2.0 [Current]
Server: 1.12.2 Beta: 3.2.0 [Current]

Thermionic Fabricator is not accepting Wax Casts preventing both heat up and crafting of all glass items for the machine. (dyed glass, cups/mugs, etc.)

JEI doesn't + the casts in.

There are quite a few posts on reddit of people having the same issue (and no one being of any help), it is repeatable. 

I have contacted the Forestry mod devs in case I was just using the mod wrong or if there was a workaround. They informed me that it is either a mod/inventory conflict or some manner of craft disabling.

I could not locate a config to adjust for my server.

**Comment by afroJezuz** [comment]
If it's easier, maybe altering the craft for the drinking glasses to glass panes instead of wax, in a Crafting table instead of the Thermionic Fabricator?

**Comment by temp1011** [comment]
Forestry issue is https://github.com/ForestryMC/ForestryMC/issues/2459

**Comment by temp1011** [comment]
I believe this is due to a conflict with baubles. On version 3.2.0 of the pack I have these mods disabled: [gist](https://gist.github.com/temp1011/6d001ceabcacc79a8447c5dc75fa2aaa). As soon as I add baubles I can't put the wax cast into the slot any more. Probably something to do with the extra slots baubles uses for itself.

Should be easy enough for you to test by removing baubles in a test world.

**Comment by temp1011** [comment]
I've narrowed this down a bit further and I think that this is a conflict between astral sorcery and forestry. I've opened an issue on their tracker here: https://github.com/HellFirePvP/AstralSorcery/issues/1191

**Comment by 016Nojr** [comment]
Fixed in a pack update coming in a few days
