### ISSUE TITLE
FTB Server Crashes on Startup

### ISSUE THREAD

**Issue by samil25** [FTBTeam/FTB-Revelation-2#357]
* **Modpack Version**: 3.2.0

* **Issue**: I downloaded the original server files from the provided link on the FTB launcher but when i try to startup the server from the .bat file, after running the ftbinstall.bat and settings.bat files, the server keeps crashing because of different mods. In the crashlog it says, it crashed because of aroma's 1997 dimension.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1ade7cda

* **Is it Repeatable?**: Yes

**Comment by rune-san** [comment]
In the crash report it still shows your max Memory assigned is "1979MB". This is not nearly enough RAM, as noted on the front page of the FTB Revelation 2 Mod.
https://www.feed-the-beast.com/projects/ftb-revelation

**A minimum of 4 GB of RAM is recommended for clients as well as servers for best performance
Latest version of JAVA 8 is recommended 
JAVA 9 is NOT supported**

This is the default configuration, so I'm assuming you simply haven't adjusted this setting yet. The Server crashes on startup because the Java instance runs out of memory to put objects in while loading.

Increase your RAM allocation in the settings.bat file to between 4GB and 6GB and test again. :)

**Comment by samil25** [comment]
> In the crash report it still shows your max Memory assigned is "1979MB". This is not nearly enough RAM, as noted on the front page of the FTB Revelation 2 Mod.
> https://www.feed-the-beast.com/projects/ftb-revelation
> 
> **A minimum of 4 GB of RAM is recommended for clients as well as servers for best performance Latest version of JAVA 8 is recommended JAVA 9 is NOT supported**
> 
> This is the default configuration, so I'm assuming you simply haven't adjusted this setting yet. The Server crashes on startup because the Java instance runs out of memory to put objects in while loading.
> 
> Increase your RAM allocation in the settings.bat file to between 4GB and 6GB and test again. :)

Thank you, I increased the RAM but i still got the crash. Here's the new crashlog
https://paste.feed-the-beast.com/view/2f5a63d3

**Comment by samil25** [comment]
Okey, I sorted out the issue. Apparently Java really doesn't like to be runned on languages other than English and since my computer's language was not, it wanted to crash. I simply solved that problem by adding  "-Duser.language=en -Duser.country=US" parameters to the settings.bat file.

**Comment by OniKageS** [comment]
Can you help me? I have the same problem but I don't know how to solve it.
