### ISSUE TITLE
root.tick.textures extreme lag

### ISSUE THREAD

**Issue by mr-extreme112** [FTBTeam/FTB-Revelation-2#366]
Hi,
i havent really found a solution to my problem, so i thought i could ask here. When playing Multiplayer i only get 1-2FPS most times, then there are periods where i can play with 100+ fps. Using the Optifine Debug Chart i narrowed it down to root.tick.textures using all my available processing power. I allocated 4-10gb, nothing made a diffrence. I get this on almost all packs, but mostly on multiplayer and Revelation. I dont have the best PC, but i think it should at least handle it with stable 30 fps. 
-Ryzen 3 2200G
-16g ram
-SSD
-R9 380x
Did anyone else have this problem and found a fix? How can i narrow it down more?
Did i miss any information thats relevant?

**Comment by rune-san** [comment]
Do you have mipmapping turned on? Mipmapping on big modpacks can crush graphics cards due to graphics card RAM requirements. If you have Mipmapping set to 4 especially, it can be rough. Can you confirm what it's set to, and if it's anything other than 0, set it to 0 and validate?

Also please ensure Optifine itself is disabled while you're doing the actual test for lag.

**Comment by mr-extreme112** [comment]
Mipmapping is set to 0, and i just tested the pack without Optifin, still the same issue. Also in Singleplayer. CPU Usage stays under 60% on all 4 cores, which seem to be loaded similarely. RAM ist not close to beeing full too, and i really doubt that this is GPU related. Im not on Enegery saving mode either. Its really annoying that i cant go into more detail using the pie chart in the debug screen, on which mod is causing it. My gpu has 4gb of ram, i dont think this would be the problem? I also turned of my IGP of the rycen chip, i dont think minecraft is using that. Im really out of ideas now. Must be something very simple, a friend of mine is playing on the same server using an laptop and has no issues at all.

**Comment by rune-san** [comment]
Since you do have an AMD GPU though, disable Animated Textures in foamfix and test again (remember, no Optifine either, as it has it's own "fixes" that we're trying to rule out).

In your foamfix.cfg file (should be in your configs folder of your Minecraft Instance), find the following line:

```
Disables texture animations. [default: false]
B:disableTextureAnimations=false
```

Set it to true:

```
Disables texture animations. [default: false]
B:disableTextureAnimations=true
```

Save the file, load your game again and test.

**Comment by mr-extreme112** [comment]
Awsome, that was the ticket. Now i get stable 100+fps even with the render distance set to 12. Thank you so much, i never would have found this. Do you by chance know why this works? Just out of curiosity. Does this only apply to AMD GPUs?

**Comment by rune-san** [comment]
I've heard of this happening on NVIDIA as well, but there seems to be much more of a problem with AMD GPUs, Minecraft's render logic, and Animated Textures. The issue has been around for quite some time for FoamFix, documented under asiekierka/FoamFix#142 . FoamFix is not maintained anymore, so there's not likely to ever be a fix for the issue.

Some "best of both worlds" can be attained by adding the VanillaFix Mod to your mods folder, and re-enabling animated textures. It allows animated textures again, but the VanillaFix Mod limits animations to only **visible** textures, not all textures, which greatly reduces the load. This is usually a performant happy medium.
