### ISSUE TITLE
CPU Usage spiking every 10-15 seconds

### ISSUE THREAD

**Issue by abraxascreations** [FTBTeam/FTB-Revelation-2#373]
* **Modpack Version**: FTB Revelation 3.2.0

* **Issue**: Game will run fine for a short period of time, then CPU usage spikes every 10-15 seconds for about 5 seconds rendering the game unplayable. 

* **Link to Log or Crash File Paste**: Game doesn't crash until I force it to stop.

* **Is it Repeatable?**: yes, every time I go to play the game this happens. Was fine on DireWolf20 modpack, only started with Revelation. 

* **Known Fix**: I have tried pasting the following into the twitch launcher and vanilla launcher (including the forge part of the vanilla launcher and none have worked "XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"

**Comment by rune-san** [comment]
Hello, even without a crash, you still need to provide a log file from while the game's running. Naturally the game operates well enough on its own, so people need to know what's unique about your install to assist. Otherwise, there's not anything to go on here.

**Comment by abraxascreations** [comment]
[crash-2020-04-30_12.02.50-client.txt](https://github.com/FTBTeam/FTB-Revelation-2/files/4562153/crash-2020-04-30_12.02.50-client.txt)
Find attached a log from yesterday.

**Comment by rune-san** [comment]
I believe you're getting spikes because Garbage Collection is having to run constantly, due to inadequate RAM:
Memory: 208724912 bytes (199 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)

2GB assigned is far below the 4GB minimum requirement. Increase the amount of RAM you have assigned for this pack to 4-6GB and re-test. Additionally, re-set your java options back to default, at least for the purpose of testing.

**Comment by abraxascreations** [comment]
I had this up at 6gb on the twitch launcher, do I have to manually do that (up the RAM), in a minecraft config file. And as for resetting Java settings, how does one accomplish that?

**Comment by rune-san** [comment]
No, but the setting you're configuring in Twitch is not making it to your Minecraft runtime. Make sure you haven't overridden your setting at the Profile Level in Twitch, or if you have, make sure your Profile is set to 6GB.

By resetting Java settings, I mean remove any extra Java parameters you've added anywhere. They should be just left to the default.

If it's too far gone (or you don't remember all the places you've made changes) try reinstalling Revelation to make sure you have a clean slate.

**Comment by abraxascreations** [comment]
I reset the JVA argument in the vanilla launcher and changed from 2gb to 6gb, and just got this crash just then. The ingame read out in Minecraft was saying I was running 6gb.

[hs_err_pid3592.log](https://github.com/FTBTeam/FTB-Revelation-2/files/4562292/hs_err_pid3592.log)

**Comment by rune-san** [comment]
This is a system issue. The error is telling you that while you have 6GB of RAM assigned to your Java game, your system is running out of RAM to assign to that Java Virtual Machine:

`Memory: 4k page, physical 16734384k(1892776k free), swap 16734384k(6404k free)`

The above shows your system had about 1.8GB of RAM free on your computer (out of 16GB), and only about 6MB in your page file free. So it sounds like you're running a ton of stuff on your system and are simply running out of RAM. A single player game should run adequately on 4GB of RAM for Minecraft, so you can try lowering it to that, but otherwise you're going to have to take a look at what you've got running on your system while you're running Minecraft and try to compensate. Otherwise you'd need to add more RAM to your system (though unless you're a Virtual Machine User, or some other Power User, most people should be more than comfortable with 16GB of RAM).
