### ISSUE TITLE
RFTools Spawner Causing CTD

### ISSUE THREAD

**Issue by SnowsongWolf** [FTBTeam/FTB-Revelation-2#374]
* **Modpack Version**: 3.2.0

* **Issue**: Attempting to place a Syringe of Thaumcraft mob "Lesser Crimson Portal" in an RFTools Spawner causes the client to crash to desktop.  The world file can no longer be loaded.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6be437e4

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thaumcraft, RFTools

* **Known Fix**: None (though I suspect adding a definition for Lesser Crimson Portal spawn amounts to RFTools will resolve)

**Comment by oliverbaumbach** [comment]
I ran into this issue as well, trying to place a Pink Wither Syringe into an RFTools Spawner. I found this related issue on the RFTools Issue tracker [https://github.com/McJtyMods/RFTools/issues/1967](https://github.com/McJtyMods/RFTools/issues/1967) , which says it is due to incorrectly defined spawner requirements.

**Comment by 016Nojr** [comment]
If this bug isnt fixed after the new pack update coming in a few days I cant fix it as the mod isnt being developed anymore
