### ISSUE TITLE
FTB Revelation cant craft item( no recipe )

### ISSUE THREAD

**Issue by Gheas** [FTBTeam/FTB-Revelation-2#392]
* **Modpack Version**: 3.2.0

* **Issue**: Hello, im trying to craft "Flux-Infused JetPlate" to craft this item i need "Energy Cell (Resonant)" but there is no craft recipe. Is there any way to get this item or is it replaced from this mod pack?

* **Mod/s Affected**: ThermalExpansion 1.12.2-5.5.4.43-universal

* **Known Fix**: 
![image]

**Comment by SirPuck** [comment]
Hello Gheas,

I hope you found out how to proceed since it's been 4 days you are waiting for an answer.
To craft this item, you need first to 
1) Craft energy Cell (the lowest)
2) craft the following upgrades : hardened, reinforced, signalum, resonant...
3) Place the energy cell on the ground, apply the upgrades in the good order

All in all, it's pretty straightforward once you get it. Then, "mine" the energy cell to get it back in your inventory.


Regards

**Comment by Gheas** [comment]
thank u very much

вт, 28 июл. 2020 г. в 16:13, MPuke <notifications@github.com>:
