### ISSUE TITLE
Update modpack with latest mod versions

### ISSUE THREAD

**Issue by SapleMyrup** [FTBTeam/FTB-Revelation-2#412]
Not an issue per say, but it would probably fix a lot of issues server owners and clients are having, I would be willing help test on my end.

**Comment by SugarD-x** [comment]
I would absolutely love to see this. The last announcement I heard for this modpack, (which was not easy to find and is very old now), said there would be at least one more update which brought the mods up to date and fixed some issues. Most of the mods were only bumped up to newer versions that were still outdated. I'm having more problems than ever now because of the bugs introduced. It would be nice if the pack received another update with all of the available fixes.

**Comment by 016Nojr** [comment]
Coming in a few days
