### ISSUE TITLE
Most of the mods (if not all) in this pack are outdated. 

### ISSUE THREAD

**Issue by MjrSilver** [FTBTeam/FTB-Revelation-2#423]
**- Modpack Version:**
 3.3.0

**- Issue:**
 Modpack seems to be outdated. 
Before the main menu it shows a gigantic list of mods saying that those mods are for an older version of Forge.
Ex.: "file ActuallyBaubles-1.12-1.1.jar is for an older version of Forge and cannot be loaded"
My Minecraft and Forge are both ver. 1.16.4 
 
**- Link to Log or Crash File Paste:**
 https://paste.feed-the-beast.com/view/27be8559
 
**- Is it Repeatable?:**
 Yes, it repeats every time I run the game
 
**- Mod/s Affected:**
![Screenshot (64)](https://user-images.githubusercontent.com/75227555/100557600-2adab880-32a2-11eb-83c3-98214b63cc9f.png)
 My gess is all of them

**Comment by rune-san** [comment]
This is by design. A modpack like this contains many, many mods. These mods are created by numerous authors for specific Minecraft versions. Going between Minecraft versions can be a monumental task for mod developers, which several mods either being drastically changed, undergoing major re-writes, or simply abandoned as newer Minecraft versions come out.

A modpack is meant to be installed and played as one complete unit (in this case with Minecraft 1.12.2, and the appropriate Forge version). Updates are meant to be done at the modpack level, by deploying the newer version and bringing in your world / configs.

**Comment by Sunekaer** [comment]
This a is 1.12 pack and won't be able to run any other version of MC
