### ISSUE TITLE
IC2 Machines producing IC2-specific plates/dusts instead of TE like rest of pack.

### ISSUE THREAD

**Issue by random51** [FTBTeam/FTB-Revelation-2#57]
* **Modpack Version**: 2.2.0

* **Issue**: IC2 machines producing IC2 dusts/plates while it looks like everything in pack is supposed to be producing COFH plates/dusts. Base IC2 plates don't show up in JEI---presumably because everything is supposed to be producing COFH plates.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: ic2/JEI

* **Known Fix**:

**Comment by Flanks255** [comment]
The fix is the same as in FTB Pyramid, pull the ini files from the jar of IC2, put them in a ic2 subfolder in the config folder, with the correct changes.
Like...
`
; Iron Ingot
minecraft:iron_ingot = thermalfoundation:material@32
; Gold Ingot
minecraft:gold_ingot = thermalfoundation:material@33
; Copper Ingot
OreDict:ingotCopper = thermalfoundation:material@320
; Tin Ingot
OreDict:ingotTin = thermalfoundation:material@321
; Silver Ingot
OreDict:ingotSilver = thermalfoundation:material@322
; Lead Ingot
OreDict:ingotLead = thermalfoundation:material@323
; Aluminum Ingot
OreDict:ingotAluminum = thermalfoundation:material@324
; Nickel Ingot
OreDict:ingotNickel = thermalfoundation:material@325
; Platinum Ingot
OreDict:ingotPlatinum = thermalfoundation:material@326
; Iridium Ingot
OreDict:ingotIridium = thermalfoundation:material@327
; Mithril Ingot
OreDict:ingotMithril = thermalfoundation:material@328
; Steel Ingot
OreDict:ingotSteel = thermalfoundation:material@352
; Electrum Ingot
OreDict:ingotElectrum = thermalfoundation:material@353
; Invar Ingot
OreDict:ingotInvar = thermalfoundation:material@354
; Bronze Ingot
OreDict:ingotBronze = thermalfoundation:material@355
; Constantan Ingot
OreDict:ingotConstantan = thermalfoundation:material@356
; Signalum Ingot
OreDict:ingotSignalum = thermalfoundation:material@357
; Lumium Ingot
OreDict:ingotLumium = thermalfoundation:material@358
; Enderium Ingot
OreDict:ingotEnderium = thermalfoundation:material@359
`
for the metal former

**Comment by tfox83** [comment]
fixed in 2.3.0
