### ISSUE TITLE
Gadgetry crashing 2.3 server

### ISSUE THREAD

**Issue by ripzeus** [FTBTeam/FTB-Revelation-2#73]
Playing around with the beta FTBRevelation-2.3.0-1.12.2.zip and came across the Gadgetry mod crashing the server.

Server will crash when any Gadgetry item is placed or removed. 

Modpack Version: Beta Modpack

Issue: Gadgetry cashing server

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/5aeb3602

Is it Repeatable?: Yes

Mod/s Affected: Gadgetry, 2.3

**Comment by ripzeus** [comment]
Created a brand new world to see if it was my world. No luck.

Here is the dump for it.

https://paste.feed-the-beast.com/view/0e45c29a

**Comment by RalphFox** [comment]
I had this problem as well. When placing the generator from gadgetry, the server would crash, and the only way to get around would be an edit or rollback.

Strangely, I attempted it on single player and it worked, so I assumed it was something that happened when I updated the server. Since you said you tried on a brand new world, perhaps not.

The alloy furnace worked to me though.

Sadly it'll take a while for the bug to be fixed because the mod was in limbo, but happily, it was recently taken by another person. So fixes to that might take a while, as there isn't even an github/issue tracker yet.

**Comment by TangoCheetahs** [comment]
After messing with Gadgetry machines (block placer, sprinkler, powered alloyer, furnace generator), I was able to crash the server. However, there are some other bugs I have found in Gadgetry (Sprinkler Dupe Bug) that may be causing the server crash. I will update when I get more information from the server Admin.

**Comment by TangoCheetahs** [comment]
The issue was reported to EpicSquid via Discord. Linking closed ticket #59 as the sprinkler issue is still in 2.3.0 and the crashing issue is in 2.3.0

**Comment by tfox83** [comment]
Mod has been removed due to lack of updates and last build was over 6 months ago.
