### ISSUE TITLE
Mod Suggestion - RFTools dimensions

### ISSUE THREAD

**Issue by raziel23x** [FTBTeam/FTB-Revelation-2#79]
https://minecraft.curseforge.com/projects/rftools-dimensions
any way of have this part of the mod added as well

**Comment by RalphFox** [comment]
Hey there. Not a maintainer or anything, just a passerby, but I'd suggest you to look on closed issues next time before opening another issue/suggestion;

It already has been suggested on #72 but was dismissed sadly.
I'd love also to have dimensions, but it's understandable because of how popular this pack is and how big is the playerbase, and how many people still sadly play on potatos.

**Comment by zaqhack** [comment]
I was actually surprised they added Twilight Forest to this pack at 2.0+ ... so, I get the "server load" problem, but I'm not sure that's "final." TF has forever been a server hog.

**Comment by tfox83** [comment]
We do not add player created DIMs to our large modpacks due to server/client performance, feel free to add it yourself if you cant play without it.  Shouldn't cause any conflicts.
